-- MySQL Script generated by MySQL Workbench
-- jue 22 feb 2024 15:15:46
-- Model: nom_applicantsdb    Version: 1.0

-- applicants system for vacancies

-- -----------------------------------------------------
-- Schema nom_applicantsdb
-- -----------------------------------------------------
-- applicants simple db schema

-- -----------------------------------------------------
-- Table `nom_user_registers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nom_user_registers` ;

CREATE TABLE IF NOT EXISTS `nom_user_registers` (
  `cod_user` VARCHAR(80) NOT NULL COMMENT 'named ic or passport code or licence number depends of country',
  `email` VARCHAR(80) NULL DEFAULT NULL COMMENT 'identification login of the user as alternate',
  `userpass` VARCHAR(80) NULL DEFAULT NULL COMMENT 'passowrd encripted by the framework',
  `api_token` VARCHAR(80) NULL DEFAULT NULL COMMENT 'api key for non password usage',
  `userlevel` VARCHAR(80) NULL DEFAULT NULL COMMENT 'from 0 as invited applicant or 1 as registered user or 5 as manager of vacancies',
  `created_at` VARCHAR(80) NOT NULL COMMENT 'YYYYMMDDHHmmss date creation of',
  `updated_at` VARCHAR(80) NOT NULL COMMENT 'YYYYMMDDHHmmss date change of',
  PRIMARY KEY (`cod_user`))
COMMENT = 'represent the internal users to access the vacancies manager';


-- -----------------------------------------------------
-- Table `nom_user_profile`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nom_user_profile` ;

CREATE TABLE IF NOT EXISTS `nom_user_profile` (
  `cod_user` VARCHAR(80) NOT NULL COMMENT 'named ic or passport code or licence number depends of country',
  `first_name` VARCHAR(80) NULL DEFAULT NULL COMMENT 'name',
  `second_name` VARCHAR(80) NULL DEFAULT NULL COMMENT 'surname',
  `last_name` VARCHAR(80) NULL DEFAULT NULL COMMENT 'named apellido in latam',
  `second_surname` VARCHAR(80) NULL DEFAULT NULL COMMENT 'second surname or appellido in latam',
  `presentation` TEXT NULL DEFAULT NULL COMMENT 'a short description of',
  `education_level` VARCHAR(80) NULL DEFAULT NULL COMMENT 'level graduated education - 1 primary - 4 univers - 5 doctor - 6 mgrs',
  `address_born` VARCHAR(80) NULL DEFAULT NULL COMMENT 'place where its born',
  `address_living` VARCHAR(80) NULL DEFAULT NULL COMMENT 'place where its currently living or sleeping',
  `first_phone` VARCHAR(80) NULL DEFAULT NULL COMMENT 'main mobile phone or local one',
  `second_phone` VARCHAR(80) NULL DEFAULT NULL COMMENT 'another phone number for contact',
  `picture_face` VARCHAR(80) NULL DEFAULT NULL COMMENT 'path photo of the presentation of their face',
  `picture_body` VARCHAR(80) NULL DEFAULT NULL COMMENT 'path photo of the full presentation of their person',
  `created_at` VARCHAR(80) NOT NULL COMMENT 'YYYYMMDDHHmmss date creation of',
  `updated_at` VARCHAR(80) NOT NULL COMMENT 'YYYYMMDDHHmmss date change of',
  PRIMARY KEY (`cod_user`))
COMMENT = 'table for the people tregistered with thier caracteristics';


-- -----------------------------------------------------
-- Table `nom_vacancies_details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nom_vacancies_details` ;

CREATE TABLE IF NOT EXISTS `nom_vacancies_details` (
  `cod_vacancies` VARCHAR(80) NOT NULL COMMENT 'id of the vacancy',
  `is_permanent` VARCHAR(80) NOT NULL DEFAULT 'P' COMMENT 'if the job is P-ermanent or T-emporally',
  `vacancies_name` TEXT NULL DEFAULT NULL COMMENT 'long title of the vacancy work, short title is at the main table',
  `vacancies_description` TEXT NULL DEFAULT NULL COMMENT 'short description of the vacancy work to offer',
  `vacancies_direction` TEXT NULL DEFAULT NULL COMMENT 'address of the position, mostly close to and not detailed',
  `vacancies_start` VARCHAR(80) NULL DEFAULT NULL COMMENT 'YYYYMMDD date of valid publication for public people',
  `vacancies_end` VARCHAR(80) NULL DEFAULT NULL COMMENT 'YYYYMMDD date of expiration of this vacancy',
  `created_at` VARCHAR(80) NOT NULL COMMENT 'YYYYMMDDHHmmss date creation of',
  `updated_at` VARCHAR(80) NOT NULL COMMENT 'YYYYMMDDHHmmss date change of',
  PRIMARY KEY (`cod_vacancies`))
COMMENT = 'the oportunities of works for future employeers';


-- -----------------------------------------------------
-- Table `nom_vacancies_tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nom_vacancies_tag` ;

CREATE TABLE IF NOT EXISTS `nom_vacancies_tag` (
  `cod_vacancies_tag` VARCHAR(80) NOT NULL COMMENT 'id of the tag for various vacancies',
  `des_vacancies_tag` TEXT NULL DEFAULT NULL COMMENT 'name category or tag .. mostly only two words allowed',
  `created_at` VARCHAR(80) NOT NULL COMMENT 'YYYYMMDDHHmmss date creation of',
  `updated_at` VARCHAR(80) NOT NULL COMMENT 'YYYYMMDDHHmmss date change of',
  PRIMARY KEY (`cod_vacancies_tag`))
COMMENT = 'used to filtering the vacancies';


-- -----------------------------------------------------
-- Table `nom_vacancies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nom_vacancies` ;

CREATE TABLE IF NOT EXISTS `nom_vacancies` (
  `cod_vacancies` VARCHAR(80) NOT NULL,
  `cod_vacancies_tag` VARCHAR(80) NOT NULL,
  `cod_location_tag` VARCHAR(80) NOT NULL,
  `vacancies_title` TEXT NULL COMMENT 'short name of the vacancie, mostly combianiton of most usefull words of title and description',
  `created_at` VARCHAR(80) NOT NULL COMMENT 'YYYYMMDDHHmmss date creation of',
  `updated_at` VARCHAR(80) NOT NULL COMMENT 'YYYYMMDDHHmmss date change of',
  PRIMARY KEY (`cod_vacancies`, `cod_vacancies_tag`, `cod_location_tag`))
COMMENT = 'main table of vacancies';


-- -----------------------------------------------------
-- Table `nom_vacancies_applicants`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nom_vacancies_applicants` ;

CREATE TABLE IF NOT EXISTS `nom_vacancies_applicants` (
  `cod_vacancies` VARCHAR(80) NOT NULL COMMENT 'vacancy that user try to apply, this is the history of both users and vacancies',
  `cod_user` VARCHAR(80) NOT NULL COMMENT 'user that try to apply for',
  `apply_at` VARCHAR(80) NULL COMMENT 'YYYYMMDDHHmmss user apply for',
  `created_at` VARCHAR(80) NOT NULL COMMENT 'YYYYMMDDHHmmss date creation of',
  `updated_at` VARCHAR(80) NOT NULL COMMENT 'YYYYMMDDHHmmss date change of',
  PRIMARY KEY (`cod_vacancies`, `cod_user`))
COMMENT = 'amount of users that applies to vacancies';


-- -----------------------------------------------------
-- Table `nom_location_tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nom_location_tag` ;

CREATE TABLE IF NOT EXISTS `nom_location_tag` (
  `cod_location_tag` VARCHAR(80) NOT NULL COMMENT 'id of the tag for various locations',
  `des_location_tag` TEXT NULL DEFAULT NULL COMMENT 'location category or tag .. mostly only two words allowed',
  `created_at` VARCHAR(80) NOT NULL COMMENT 'YYYYMMDDHHmmss date creation of',
  `updated_at` VARCHAR(80) NOT NULL COMMENT 'YYYYMMDDHHmmss date change of',
  PRIMARY KEY (`cod_location_tag`))
COMMENT = 'used to filtering the vacancies by locations as tag associat' /* comment truncated */ /*ion*/;


-- -----------------------------------------------------
-- Data for table `nom_user_registers`
-- -----------------------------------------------------
INSERT INTO `nom_user_registers` (`cod_user`, `email`, `userpass`, `api_token`, `userlevel`, `created_at`, `updated_at`) VALUES ('123', 'demo', 'demo', 'token', '1', '20230101', '20230101');


-- -----------------------------------------------------
-- Data for table `nom_user_profile`
-- -----------------------------------------------------
INSERT INTO `nom_user_profile` (`cod_user`, `first_name`, `second_name`, `last_name`, `second_surname`, `presentation`, `education_level`, `address_born`, `address_living`, `first_phone`, `second_phone`, `picture_face`, `picture_body`, `created_at`, `updated_at`) VALUES ('123', 'name', 'surape', 'apellid', 'overname', 'i am a employer', '2', 'venezuela, city, address, home number', 'colombia, city, address, home floor', '+582122661610', '+502125556677', 'storage/files/face.jpeg', NULL, '20240101', '20240101');


-- -----------------------------------------------------
-- Data for table `nom_vacancies_details`
-- -----------------------------------------------------
INSERT INTO `nom_vacancies_details` (`cod_vacancies`, `is_permanent`, `vacancies_name`, `vacancies_description`, `vacancies_direction`, `vacancies_start`, `vacancies_end`, `created_at`, `updated_at`) VALUES ('1', '0', 'Gerente', 'Manager for loren ipsum loren ipsum', 'Calle paez cruze con bolivar', '20240131', '20240220', '20240130', '20240130');


-- -----------------------------------------------------
-- Data for table `nom_vacancies_tag`
-- -----------------------------------------------------
INSERT INTO `nom_vacancies_tag` (`cod_vacancies_tag`, `des_vacancies_tag`, `created_at`, `updated_at`) VALUES ('Legal', 'Abogado, Politica, Policia, Juez, Jurado', '20240101', '20240101');
INSERT INTO `nom_vacancies_tag` (`cod_vacancies_tag`, `des_vacancies_tag`, `created_at`, `updated_at`) VALUES ('Artes', 'Diseño grafico, Marqueting', '20240101', '20240101');
INSERT INTO `nom_vacancies_tag` (`cod_vacancies_tag`, `des_vacancies_tag`, `created_at`, `updated_at`) VALUES ('Salud', 'Agronomía, Fisioterapia, Antropología, Enfermería, Odontología', '20240101', '20240101');
INSERT INTO `nom_vacancies_tag` (`cod_vacancies_tag`, `des_vacancies_tag`, `created_at`, `updated_at`) VALUES ('Admin', 'Archivología, Gerente, Sub Gerente, Administradora', '20240101', '20240101');
INSERT INTO `nom_vacancies_tag` (`cod_vacancies_tag`, `des_vacancies_tag`, `created_at`, `updated_at`) VALUES ('Ingenieria', 'Civil, Arquitectura, Soporte Tecnico, Electrica, Mecanica', '20240101', '20240101');
INSERT INTO `nom_vacancies_tag` (`cod_vacancies_tag`, `des_vacancies_tag`, `created_at`, `updated_at`) VALUES ('Ciencias', 'Contaduría, Computación, Estadística, Reportes, Geografía, Química', '20240101', '20240101');
INSERT INTO `nom_vacancies_tag` (`cod_vacancies_tag`, `des_vacancies_tag`, `created_at`, `updated_at`) VALUES ('Comunica', 'Abogado, Politica, Gerencia, Auditoria, Filosofía, Idiomas, Psicología, Comunicacion', '20240101', '20240101');
INSERT INTO `nom_vacancies_tag` (`cod_vacancies_tag`, `des_vacancies_tag`, `created_at`, `updated_at`) VALUES ('Economia', 'Negocios, Compras, Tesoreria, Finanzas, Economia', '20240101', '20240101');
INSERT INTO `nom_vacancies_tag` (`cod_vacancies_tag`, `des_vacancies_tag`, `created_at`, `updated_at`) VALUES ('Educacion', 'Educacion, Cursos, Historia', '20240101', '20240101');
INSERT INTO `nom_vacancies_tag` (`cod_vacancies_tag`, `des_vacancies_tag`, `created_at`, `updated_at`) VALUES ('Procesos', 'Procesos Industriales, Gerencia de procesos', '20240101', '20240101');


-- -----------------------------------------------------
-- Data for table `nom_vacancies`
-- -----------------------------------------------------
INSERT INTO `nom_vacancies` (`cod_vacancies`, `cod_vacancies_tag`, `cod_location_tag`, `vacancies_title`, `created_at`, `updated_at`) VALUES ('1', 'Admin', DEFAULT, 'Gerente for manager', '20240131', '20240131');


-- -----------------------------------------------------
-- Data for table `nom_location_tag`
-- -----------------------------------------------------
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('AFG', ' Afghanistan[b]', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('ALA', ' Åland Islands', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('ALB', ' Albania', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('DZA', ' Algeria', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('ASM', ' American Samoa', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('AND', ' Andorra', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('AGO', ' Angola', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('AIA', ' Anguilla', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('ATA', ' Antarctica', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('ATG', ' Antigua and Barbuda', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('ARG', ' Argentina', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('ARM', ' Armenia', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('ABW', ' Aruba', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('AUS', ' Australia', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('AUT', ' Austria', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('AZE', ' Azerbaijan', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('BHS', ' Bahamas', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('BHR', ' Bahrain', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('BGD', ' Bangladesh', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('BRB', ' Barbados', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('BLR', ' Belarus', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('BEL', ' Belgium', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('BLZ', ' Belize', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('BEN', ' Benin', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('BMU', ' Bermuda', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('BTN', ' Bhutan', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('BOL', ' Bolivia (Plurinational State of)', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('BES', ' Bonaire', ' Sint Eustatius and Saba[c]', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('BIH', ' Bosnia and Herzegovina', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('BWA', ' Botswana', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('BVT', ' Bouvet Island', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('BRA', ' Brazil', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('IOT', ' British Indian Ocean Territory', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('BRN', ' Brunei Darussalam', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('BGR', ' Bulgaria', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('BFA', ' Burkina Faso', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('BDI', ' Burundi', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('CPV', ' Cabo Verde', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('KHM', ' Cambodia', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('CMR', ' Cameroon', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('CAN', ' Canada', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('CYM', ' Cayman Islands', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('CAF', ' Central African Republic', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('TCD', ' Chad', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('CHL', ' Chile', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('CHN', ' China[b]', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('CXR', ' Christmas Island', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('CCK', ' Cocos (Keeling) Islands', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('COL', ' Colombia', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('COM', ' Comoros', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('COG', ' Congo', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('COD', ' Congo Democratic Republic of', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('COK', ' Cook Islands', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('CRI', ' Costa Rica', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('CIV', ' Côte d\'Ivoire', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('HRV', ' Croatia', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('CUB', ' Cuba', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('CUW', ' Curaçao', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('CYP', ' Cyprus[b]', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('CZE', ' Czechia', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('DNK', ' Denmark', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('DJI', ' Djibouti', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('DMA', ' Dominica', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('DOM', ' Dominican Republic', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('ECU', ' Ecuador', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('EGY', ' Egypt', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('SLV', ' El Salvador', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('GNQ', ' Equatorial Guinea', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('ERI', ' Eritrea', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('EST', ' Estonia', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('SWZ', ' Eswatini', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('ETH', ' Ethiopia', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('FLK', ' Falkland Islands (Malvinas)[b]', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('FRO', ' Faroe Islands', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('FJI', ' Fiji', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('FIN', ' Finland', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('FRA', ' France', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('GUF', ' French Guiana', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('PYF', ' French Polynesia', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('ATF', ' French Southern Territories', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('GAB', ' Gabon', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('GMB', ' Gambia', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('GEO', ' Georgia', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('DEU', ' Germany', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('GHA', ' Ghana', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('GIB', ' Gibraltar', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('GRC', ' Greece', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('GRL', ' Greenland', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('GRD', ' Grenada', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('GLP', ' Guadeloupe', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('GUM', ' Guam', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('GTM', ' Guatemala', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('GGY', ' Guernsey', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('GIN', ' Guinea', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('GNB', ' Guinea-Bissau', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('GUY', ' Guyana', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('HTI', ' Haiti', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('HMD', ' Heard Island and McDonald Islands', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('VAT', ' Holy See', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('HND', ' Honduras', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('HKG', ' Hong Kong', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('HUN', ' Hungary', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('ISL', ' Iceland', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('IND', ' India', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('IDN', ' Indonesia', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('IRN', ' Iran (Islamic Republic of)', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('IRQ', ' Iraq', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('IRL', ' Ireland', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('IMN', ' Isle of Man', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('ISR', ' Israel', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('ITA', ' Italy', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('JAM', ' Jamaica', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('JPN', ' Japan', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('JEY', ' Jersey', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('JOR', ' Jordan', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('KAZ', ' Kazakhstan', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('KEN', ' Kenya', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('KIR', ' Kiribati', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('PRK', ' Korea (Democratic People\'s Republic of)', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('KOR', ' Korea', ' Republic of', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('KWT', ' Kuwait', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('KGZ', ' Kyrgyzstan', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('LAO', ' Lao People\'s Democratic Republic', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('LVA', ' Latvia', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('LBN', ' Lebanon', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('LSO', ' Lesotho', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('LBR', ' Liberia', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('LBY', ' Libya', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('LIE', ' Liechtenstein', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('LTU', ' Lithuania', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('LUX', ' Luxembourg', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('MAC', ' Macao', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('MDG', ' Madagascar', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('MWI', ' Malawi', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('MYS', ' Malaysia', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('MDV', ' Maldives', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('MLI', ' Mali', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('MLT', ' Malta', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('MHL', ' Marshall Islands', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('MTQ', ' Martinique', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('MRT', ' Mauritania', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('MUS', ' Mauritius', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('MYT', ' Mayotte', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('MEX', ' Mexico', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('FSM', ' Micronesia (Federated States of)', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('MDA', ' Moldova', ' Republic of', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('MCO', ' Monaco', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('MNG', ' Mongolia', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('MNE', ' Montenegro', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('MSR', ' Montserrat', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('MAR', ' Morocco', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('MOZ', ' Mozambique', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('MMR', ' Myanmar', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('NAM', ' Namibia', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('NRU', ' Nauru', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('NPL', ' Nepal', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('NLD', ' Netherlands', ' Kingdom of the', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('NCL', ' New Caledonia', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('NZL', ' New Zealand', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('NIC', ' Nicaragua', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('NER', ' Niger', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('NGA', ' Nigeria', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('NIU', ' Niue', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('NFK', ' Norfolk Island', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('MKD', ' North Macedonia', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('MNP', ' Northern Mariana Islands', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('NOR', ' Norway', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('OMN', ' Oman', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('PAK', ' Pakistan', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('PLW', ' Palau', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('PSE', ' Palestine', ' State of[b]', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('PAN', ' Panama', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('PNG', ' Papua New Guinea', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('PRY', ' Paraguay', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('PER', ' Peru', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('PHL', ' Philippines', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('PCN', ' Pitcairn', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('POL', ' Poland', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('PRT', ' Portugal', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('PRI', ' Puerto Rico', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('QAT', ' Qatar', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('REU', ' Réunion', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('ROU', ' Romania', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('RUS', ' Russian Federation', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('RWA', ' Rwanda', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('BLM', ' Saint Barthélemy', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('KNA', ' Saint Kitts and Nevis', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('LCA', ' Saint Lucia', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('MAF', ' Saint Martin (French part)', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('SPM', ' Saint Pierre and Miquelon', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('VCT', ' Saint Vincent and the Grenadines', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('WSM', ' Samoa', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('SMR', ' San Marino', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('STP', ' Sao Tome and Principe', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('SAU', ' Saudi Arabia', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('SEN', ' Senegal', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('SRB', ' Serbia', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('SYC', ' Seychelles', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('SLE', ' Sierra Leone', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('SGP', ' Singapore', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('SXM', ' Sint Maarten (Dutch part)', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('SVK', ' Slovakia', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('SVN', ' Slovenia', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('SLB', ' Solomon Islands', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('SOM', ' Somalia', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('ZAF', ' South Africa', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('SGS', ' South Georgia and the South Sandwich Islands', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('SSD', ' South Sudan', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('ESP', ' Spain', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('LKA', ' Sri Lanka', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('SDN', ' Sudan', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('SUR', ' Suriname', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('SJM', ' Svalbard and Jan Mayen[e]', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('SWE', ' Sweden', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('CHE', ' Switzerland', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('SYR', ' Syrian Arab Republic', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('TWN', ' Taiwan', ' Province of China[b]', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('TJK', ' Tajikistan', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('TZA', ' Tanzania', ' United Republic of', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('THA', ' Thailand', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('TLS', ' Timor-Leste', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('TGO', ' Togo', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('TKL', ' Tokelau', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('TON', ' Tonga', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('TTO', ' Trinidad and Tobago', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('TUN', ' Tunisia', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('TUR', ' Türkiye', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('TKM', ' Turkmenistan', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('TCA', ' Turks and Caicos Islands', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('TUV', ' Tuvalu', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('UGA', ' Uganda', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('UKR', ' Ukraine', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('ARE', ' United Arab Emirates', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('GBR', ' United Kingdom of Great Britain and Northern Ireland', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('USA', ' United States of America', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('UMI', ' United States Minor Outlying Islands[f]', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('URY', ' Uruguay', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('UZB', ' Uzbekistan', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('VUT', ' Vanuatu', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('VEN', ' Venezuela (Bolivarian Republic of)', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('VNM', ' Viet Nam', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('VGB', ' Virgin Islands (British)', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('VIR', ' Virgin Islands (U.S.)', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('WLF', ' Wallis and Futuna', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('ESH', ' Western Sahara[b]', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('YEM', ' Yemen', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('ZMB', ' Zambia', '20230101', '20230101');
INSERT INTO `nom_location_tag` (`cod_location_tag`, `des_location_tag`, `created_at`, `updated_at`) VALUES ('ZWE', ' Zimbabwe', '20230101', '20230101');


