-- SQL Script generated by PICCORO Lenz McKAY
-- jue 03 ago 2023 11:56:07
-- Model: New Model    Version: 1.0

-- -----------------------------------------------------
-- Schema applicantsdb Data dictionary
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(80) NOT NULL DEFAULT '' COMMENT 'identification login of the user',
  `encrypted_password` VARCHAR(80) NOT NULL DEFAULT '' COMMENT 'passowrd encripted by the framework',
  `reset_password_token` VARCHAR(80) NULL DEFAULT NULL COMMENT 'used in future for passwork recovery by stimulus',
  `reset_password_sent_at` DATETIME(6) NULL DEFAULT NULL COMMENT 'used in future for passwork recovery by stimulus',
  `remember_created_at` DATETIME(6) NULL DEFAULT NULL COMMENT 'mark for creation user',
  `created_at` DATETIME(6) NOT NULL COMMENT 'date creation of',
  `updated_at` DATETIME(6) NOT NULL COMMENT 'date change of',
  PRIMARY KEY (`id`))
COMMENT = 'represent the internal users to access the vacancies manager';


-- -----------------------------------------------------
-- Table `vacancies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vacancies` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'id of the vacancy',
  `fixed` VARCHAR(80) NULL DEFAULT NULL COMMENT 'If the job is permanent or temporary',
  `name` VARCHAR(80) NULL DEFAULT NULL COMMENT 'title of the vacancy work',
  `description` VARCHAR(80) NULL DEFAULT NULL COMMENT 'short description of the vacancy work to offer',
  `direction` VARCHAR(80) NULL DEFAULT NULL COMMENT 'address of the position, mostly close to and not detailed',
  `start` DATE NULL DEFAULT NULL COMMENT 'date of valid publication for public people',
  `end` DATE NULL DEFAULT NULL COMMENT 'date of expiration of this vacancy',
  `created_at` DATETIME(6) NOT NULL COMMENT 'date creation of',
  `updated_at` DATETIME(6) NOT NULL COMMENT 'date change of',
  PRIMARY KEY (`id`))
COMMENT = 'the oportunities of works for future employeers';


-- -----------------------------------------------------
-- Table `applicants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `applicants` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(80) NULL DEFAULT NULL COMMENT 'name',
  `second_name` VARCHAR(80) NULL DEFAULT NULL COMMENT 'surname',
  `last_name` VARCHAR(80) NULL DEFAULT NULL COMMENT 'named apellido in latam',
  `second_surname` VARCHAR(80) NULL DEFAULT NULL COMMENT 'second surname or appellido in latam',
  `identification` INT NULL DEFAULT NULL COMMENT 'named ic or passport code or licence number',
  `presentation` VARCHAR(80) NULL DEFAULT NULL COMMENT 'a short description of their skills',
  `school` VARCHAR(80) NULL DEFAULT NULL COMMENT 'named school graduate',
  `address` VARCHAR(80) NULL DEFAULT NULL COMMENT 'place where its currently living or sleeping',
  `university` VARCHAR(80) NULL DEFAULT NULL COMMENT 'if graduated the name of',
  `first_phone` INT NULL DEFAULT NULL COMMENT 'main mobile phone or local one',
  `second_phone` INT NULL DEFAULT NULL COMMENT 'another phone number for contact',
  `email` VARCHAR(80) NULL DEFAULT NULL COMMENT 'email for contact',
  `banks` VARCHAR(80) NULL DEFAULT NULL COMMENT 'the name of the bank to receive salary',
  `linkeding` VARCHAR(80) NULL DEFAULT NULL COMMENT 'url of profile in linkedin',
  `computrabajo` VARCHAR(80) NULL DEFAULT NULL COMMENT 'url profile of computrabajo',
  `check` INT NULL DEFAULT NULL COMMENT 'a flag for managers to check if this person was already checked or no for such vacancy',
  `vacancy_id` INT NOT NULL COMMENT 'the id of the vacancy where this person wans or will be applied',
  `created_at` DATETIME(6) NOT NULL COMMENT 'date creation of',
  `updated_at` DATETIME(6) NOT NULL COMMENT 'date change of',
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_rails_33541ee91d`
    FOREIGN KEY (`vacancy_id`)
    REFERENCES `vacancies` (`id`))
COMMENT = 'table for the people that wants to postulate to vacancies';

CREATE INDEX `fk_rails_33541ee91d` ON `applicants` (`vacancy_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `managers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `managers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(80) NULL DEFAULT NULL COMMENT 'human name of a user linked',
  `rol` VARCHAR(80) NULL DEFAULT NULL COMMENT 'represent the rol description',
  `user_id` INT NOT NULL COMMENT 'linked user to this rol',
  `created_at` DATETIME(6) NOT NULL COMMENT 'date creation of',
  `updated_at` DATETIME(6) NOT NULL COMMENT 'date change of',
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_rails_1306270b4d`
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`id`))
COMMENT = 'represent the differents people levels of access';

CREATE INDEX `fk_rails_1306270b4d` ON `managers` (`user_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `clasifications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clasifications` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(80) NULL DEFAULT NULL COMMENT 'name category',
  `created_at` DATETIME(6) NOT NULL COMMENT 'date of creation',
  `updated_at` DATETIME(6) NOT NULL COMMENT 'date of change',
  PRIMARY KEY (`id`))
COMMENT = 'used to filtering the vacancies';


-- -----------------------------------------------------
-- Data for table `vacancies`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `vacancies` (`id`, `fixed`, `name`, `description`, `direction`, `start`, `end`, `created_at`, `updated_at`) VALUES (1, '0', 'Gerente', 'Manager for loren ipsum loren ipsum', 'Calle paez cruze con bolivar', NULL, NULL, DEFAULT, DEFAULT);

COMMIT;

