-- MySQL Script generated by MySQL Workbench
-- mar 20 feb 2024 15:06:00
-- Model: nom_applicantsdb    Version: 1.0

-- applicants system for vacancies

-- -----------------------------------------------------
-- Schema nom_applicantsdb
-- -----------------------------------------------------
-- applicants simple db schema
-- -----------------------------------------------------
-- Schema sys_systemas
-- -----------------------------------------------------
-- DB central

-- -----------------------------------------------------
-- Table `nom_user_registers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nom_user_registers` ;

CREATE TABLE IF NOT EXISTS `nom_user_registers` (
  `cod_user` VARCHAR(80) NOT NULL COMMENT 'named ic or passport code or licence number depends of country',
  `email` VARCHAR(80) NULL DEFAULT NULL COMMENT 'identification login of the user as alternate',
  `userpass` VARCHAR(80) NULL DEFAULT NULL COMMENT 'passowrd encripted by the framework',
  `api_token` VARCHAR(80) NULL DEFAULT NULL COMMENT 'api key for non password usage',
  `userlevel` VARCHAR(80) NULL DEFAULT NULL COMMENT 'from 0 as invited applicant or 1 as registered user or 5 as manager of vacancies',
  `created_at` VARCHAR(80) NOT NULL COMMENT 'YYYYMMDDHHmmss date creation of',
  `updated_at` VARCHAR(80) NOT NULL COMMENT 'YYYYMMDDHHmmss date change of',
  PRIMARY KEY (`cod_user`))
COMMENT = 'represent the internal users to access the vacancies manager';


-- -----------------------------------------------------
-- Table `nom_user_profile`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nom_user_profile` ;

CREATE TABLE IF NOT EXISTS `nom_user_profile` (
  `cod_user` VARCHAR(80) NOT NULL COMMENT 'named ic or passport code or licence number depends of country',
  `first_name` VARCHAR(80) NULL DEFAULT NULL COMMENT 'name',
  `second_name` VARCHAR(80) NULL DEFAULT NULL COMMENT 'surname',
  `last_name` VARCHAR(80) NULL DEFAULT NULL COMMENT 'named apellido in latam',
  `second_surname` VARCHAR(80) NULL DEFAULT NULL COMMENT 'second surname or appellido in latam',
  `presentation` TEXT NULL DEFAULT NULL COMMENT 'a short description of',
  `education_level` VARCHAR(80) NULL DEFAULT NULL COMMENT 'level graduated education - 1 primary - 4 univers - 5 doctor - 6 mgrs',
  `address_born` VARCHAR(80) NULL DEFAULT NULL COMMENT 'place where its born',
  `address_living` VARCHAR(80) NULL DEFAULT NULL COMMENT 'place where its currently living or sleeping',
  `first_phone` VARCHAR(80) NULL DEFAULT NULL COMMENT 'main mobile phone or local one',
  `second_phone` VARCHAR(80) NULL DEFAULT NULL COMMENT 'another phone number for contact',
  `picture_face` VARCHAR(80) NULL DEFAULT NULL COMMENT 'path photo of the presentation of their face',
  `picture_body` VARCHAR(80) NULL DEFAULT NULL COMMENT 'path photo of the full presentation of their person',
  `created_at` VARCHAR(80) NOT NULL COMMENT 'YYYYMMDDHHmmss date creation of',
  `updated_at` VARCHAR(80) NOT NULL COMMENT 'YYYYMMDDHHmmss date change of',
  PRIMARY KEY (`cod_user`))
COMMENT = 'table for the people tregistered with thier caracteristics';


-- -----------------------------------------------------
-- Table `nom_vacancies_details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nom_vacancies_details` ;

CREATE TABLE IF NOT EXISTS `nom_vacancies_details` (
  `cod_vacancies` VARCHAR(80) NOT NULL COMMENT 'id of the vacancy',
  `is_permanent` VARCHAR(80) NOT NULL DEFAULT 'P' COMMENT 'if the job is P-ermanent or T-emporally',
  `vacancies_name` TEXT NULL DEFAULT NULL COMMENT 'long title of the vacancy work, short title is at the main table',
  `vacancies_description` TEXT NULL DEFAULT NULL COMMENT 'short description of the vacancy work to offer',
  `vacancies_direction` TEXT NULL DEFAULT NULL COMMENT 'address of the position, mostly close to and not detailed',
  `vacancies_start` VARCHAR(80) NULL DEFAULT NULL COMMENT 'YYYYMMDD date of valid publication for public people',
  `vacancies_end` VARCHAR(80) NULL DEFAULT NULL COMMENT 'YYYYMMDD date of expiration of this vacancy',
  `created_at` VARCHAR(80) NOT NULL COMMENT 'YYYYMMDDHHmmss date creation of',
  `updated_at` VARCHAR(80) NOT NULL COMMENT 'YYYYMMDDHHmmss date change of',
  PRIMARY KEY (`cod_vacancies`))
COMMENT = 'the oportunities of works for future employeers';


-- -----------------------------------------------------
-- Table `nom_vacancies_tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nom_vacancies_tag` ;

CREATE TABLE IF NOT EXISTS `nom_vacancies_tag` (
  `cod_vacancies_tag` VARCHAR(80) NOT NULL COMMENT 'id of the tag for various vacancies',
  `des_vacancies_tag` TEXT NULL DEFAULT NULL COMMENT 'name category or tag .. mostly only two words allowed',
  `created_at` VARCHAR(80) NOT NULL COMMENT 'YYYYMMDDHHmmss date creation of',
  `updated_at` VARCHAR(80) NOT NULL COMMENT 'YYYYMMDDHHmmss date change of',
  PRIMARY KEY (`cod_vacancies_tag`))
COMMENT = 'used to filtering the vacancies';


-- -----------------------------------------------------
-- Table `nom_vacancies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nom_vacancies` ;

CREATE TABLE IF NOT EXISTS `nom_vacancies` (
  `cod_vacancies` VARCHAR(80) NOT NULL,
  `cod_vacancies_tag` VARCHAR(80) NOT NULL,
  `vacancies_title` TEXT NULL COMMENT 'short name of the vacancie, mostly combianiton of most usefull words of title and description',
  `created_at` VARCHAR(80) NOT NULL COMMENT 'YYYYMMDDHHmmss date creation of',
  `updated_at` VARCHAR(80) NOT NULL COMMENT 'YYYYMMDDHHmmss date change of',
  PRIMARY KEY (`cod_vacancies`, `cod_vacancies_tag`))
ENGINE = InnoDB
COMMENT = 'main table of vacancies';


-- -----------------------------------------------------
-- Table `nom_vacancies_applicants`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nom_vacancies_applicants` ;

CREATE TABLE IF NOT EXISTS `nom_vacancies_applicants` (
  `cod_vacancies` VARCHAR(80) NOT NULL COMMENT 'vacancy that user try to apply, this is the history of both users and vacancies',
  `cod_user` VARCHAR(80) NOT NULL COMMENT 'user that try to apply for',
  `apply_at` VARCHAR(80) NULL COMMENT 'YYYYMMDDHHmmss user apply for',
  `created_at` VARCHAR(80) NOT NULL COMMENT 'YYYYMMDDHHmmss date creation of',
  `updated_at` VARCHAR(80) NOT NULL COMMENT 'YYYYMMDDHHmmss date change of',
  PRIMARY KEY (`cod_vacancies`, `cod_user`))
ENGINE = InnoDB
COMMENT = 'amount of users that applies to vacancies';


-- -----------------------------------------------------
-- Table `adm_entidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `adm_entidad` ;

CREATE TABLE IF NOT EXISTS `adm_entidad` (
  `cod_entidad` VARCHAR(40) NOT NULL COMMENT 'codger entidad o id sucursal que contiene el sello implicito',
  `cod_juridico` VARCHAR(40) NOT NULL COMMENT 'codigo razon social que la representa, ojo no quienes le vende o a quienes',
  `cod_sello` VARCHAR(40) NOT NULL COMMENT 'sello del lugar',
  `cod_msc` VARCHAR(40) NOT NULL COMMENT 'codigo msc del lugar',
  `abr_zona` VARCHAR(40) NOT NULL COMMENT 'siglas de la zona del pais de esta entidad',
  `abr_entidad` VARCHAR(40) NOT NULL COMMENT 'abrebiacion de esta entidad',
  `des_entidad` VARCHAR(400) NOT NULL COMMENT 'descripcion sucursal o departamento',
  `status` VARCHAR(40) NOT NULL COMMENT 'ACTIVA|INACTIVA|CERRADA|SUSPENDIDA',
  `tipo_entidad` VARCHAR(40) NOT NULL DEFAULT 'NORMAL' COMMENT 'ADMINISTRATIVA|NORMAL',
  `clase_entidad` VARCHAR(40) NULL DEFAULT 'SUCURSAL' COMMENT 'TIENDA|OFICINA|DEPARTAMENTO|GRUPO',
  `num_telefonofijo` VARCHAR(40) NULL DEFAULT NULL COMMENT 'Numero telefono fijo',
  `num_extension` VARCHAR(40) NULL DEFAULT NULL,
  `num_celularfijo` VARCHAR(40) NULL DEFAULT NULL COMMENT 'Numero telefono celular asignado por la empresa si aplica',
  `intranet_administradora` VARCHAR(40) NULL DEFAULT NULL COMMENT 'Nombre del usuario administradora o responsable que no es el gerente o jefe de la entidad',
  `intranet_encargado1` VARCHAR(40) NULL DEFAULT NULL COMMENT 'Nombre encargado o gerente de esta entidad',
  `intranet_encargado2` VARCHAR(40) NULL DEFAULT NULL COMMENT 'identificador del empleado subgerente',
  `sessionflag` VARCHAR(40) NULL DEFAULT NULL COMMENT 'YYYYMMDD+.+codger+.+sello+.+idusuarioointranet quien altero',
  `sessionficha` VARCHAR(40) NULL DEFAULT NULL COMMENT 'YYYYMMDD+.+codger+.+sello+.+idusuarioointranet quien creo esta fila',
  PRIMARY KEY (`cod_entidad`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'las entidades, que son o sucursales o tiendas u/o oficinas i' /* comment truncated */ /*ncluso departamentos o virtuales*/;


-- -----------------------------------------------------
-- Table `adm_entidad_localidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `adm_entidad_localidad` ;

CREATE TABLE IF NOT EXISTS `adm_entidad_localidad` (
  `cod_entidad` VARCHAR(40) NOT NULL COMMENT 'entidad que contiene la localidad (su sitio)',
  `cod_localidad` VARCHAR(40) NOT NULL COMMENT 'localidad de la entidad (el sitio)',
  `sessionflag` VARCHAR(40) NULL DEFAULT NULL COMMENT 'YYYYMMDD+.+codger+.+sello+.+idusuarioointranet quien altero',
  `sessionficha` VARCHAR(40) NULL DEFAULT NULL COMMENT 'YYYYMMDD+.+codger+.+sello+.+idusuarioointranet quien lo creo',
  PRIMARY KEY (`cod_entidad`, `cod_localidad`))
COMMENT = 'relacion localidad entidad EN DONDE OPERA la entidad de usua' /* comment truncated */ /*rios*/;


-- -----------------------------------------------------
-- Table `adm_entidad_proveedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `adm_entidad_proveedor` ;

CREATE TABLE IF NOT EXISTS `adm_entidad_proveedor` (
  `cod_entidad` VARCHAR(40) NOT NULL COMMENT 'codigo de la entidad cliente',
  `cod_juridico` VARCHAR(40) NOT NULL COMMENT 'codigo del proveedor que le vende',
  `sessionflag` VARCHAR(40) NULL DEFAULT NULL COMMENT 'YYYYMMDD+.+codger+.+sello+.+idusuarioointranet quien altero',
  `sessionficha` VARCHAR(40) NULL DEFAULT NULL COMMENT 'YYYYMMDD+.+codger+.+sello+.+idusuarioointranet quien lo creo',
  PRIMARY KEY (`cod_juridico`, `cod_entidad`))
COMMENT = 'proveedores q le venden a la entidad sucursal oficina o empr' /* comment truncated */ /*esa o de quienes compra, ojo no es la razon juridica de ella*/;


-- -----------------------------------------------------
-- Table `adm_entidad_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `adm_entidad_usuario` ;

CREATE TABLE IF NOT EXISTS `adm_entidad_usuario` (
  `cod_entidad` VARCHAR(40) NOT NULL COMMENT 'entidad asociado',
  `intranet` VARCHAR(40) NOT NULL COMMENT 'usuario relacionado',
  `sessionflag` VARCHAR(40) NULL DEFAULT NULL COMMENT 'YYYYMMDD+.+codger+.+sello+.+idusuarioointranet quien altero',
  `sessionficha` VARCHAR(40) NULL DEFAULT NULL COMMENT 'YYYYMMDD+.+codger+.+sello+.+idusuarioointranet quien lo creo',
  PRIMARY KEY (`cod_entidad`, `intranet`))
COMMENT = 'relacion usuario y entidad  EN QUE cumple funciones';


-- -----------------------------------------------------
-- Table `adm_ind_ventagasto_eficiencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `adm_ind_ventagasto_eficiencia` ;

CREATE TABLE IF NOT EXISTS `adm_ind_ventagasto_eficiencia` (
  `cod_indicador` VARCHAR(40) NOT NULL COMMENT 'Indicador de llave primaria',
  `cod_entidad` VARCHAR(40) NOT NULL COMMENT 'entidad sucursal o departamento analizar',
  `mon_gastototal` DECIMAL(20,2) NULL DEFAULT NULL COMMENT 'monto total gasto del fecha_mes y entidad',
  `mon_ventatotal` DECIMAL(20,2) NULL DEFAULT NULL COMMENT 'venta total del fecha_mes y entidad',
  `fecha_mes` VARCHAR(40) NOT NULL COMMENT 'YYYYMM de los montos',
  `sessionficha` VARCHAR(40) NULL DEFAULT NULL COMMENT 'yyyymmdd . codger . intranet quien lo creo',
  `sessionflag` VARCHAR(40) NULL DEFAULT NULL COMMENT 'yyyymmdd . codger . intranet quien altero',
  PRIMARY KEY (`cod_indicador`))
COMMENT = 'datos indicador de gasto, respecto ventas';


-- -----------------------------------------------------
-- Table `adm_juridico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `adm_juridico` ;

CREATE TABLE IF NOT EXISTS `adm_juridico` (
  `cod_juridico` VARCHAR(40) NOT NULL COMMENT 'codigo proveedor o ente juridico',
  `cod_rif` VARCHAR(40) NULL DEFAULT NULL COMMENT 'rif de esta razon social',
  `des_razonsocial` VARCHAR(400) NULL DEFAULT NULL COMMENT 'razon social o nombre de la empresa',
  `tipo_juridico` VARCHAR(40) NULL DEFAULT NULL,
  `estado` VARCHAR(40) NULL DEFAULT NULL COMMENT 'ACTIVO|CERRADO si cerrado debe tener fecha cerrado',
  `fecha_creado` VARCHAR(40) NULL DEFAULT NULL COMMENT 'YYYYMMDD cuando abrio o empezo ser legal',
  `fecha_cerrado` VARCHAR(40) NULL DEFAULT NULL COMMENT 'YYYYMMDD cuando cerro o dejo de funcionar',
  `sessionflag` VARCHAR(40) NULL DEFAULT NULL COMMENT 'YYYYMMDD.codger.sello.intranetoidusuario',
  `sessionficha` VARCHAR(40) NULL DEFAULT NULL,
  PRIMARY KEY (`cod_juridico`))
COMMENT = 'un ente juridico o personal de cada rif DATO SENSIBLE (prove' /* comment truncated */ /*edor)*/;


-- -----------------------------------------------------
-- Table `adm_localidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `adm_localidad` ;

CREATE TABLE IF NOT EXISTS `adm_localidad` (
  `cod_localidad` VARCHAR(40) NOT NULL COMMENT 'codigo de esta ubicacion',
  `des_localidad` VARCHAR(200) NULL DEFAULT NULL COMMENT 'nobre de la ciudad, campo, casa o ubicacion',
  `des_direccion` VARCHAR(400) NULL DEFAULT NULL COMMENT 'detalles de este sitio, direccion completa',
  `tipo_localidad` VARCHAR(40) NULL DEFAULT NULL COMMENT 'ADMINISTRATIVA|SUCURSAL|ESPECIAL',
  `estado` VARCHAR(40) NULL DEFAULT NULL COMMENT 'ACTIVA|PERDIDA|CERRADA',
  `sessionflag` VARCHAR(40) NULL DEFAULT NULL COMMENT 'YYYYMMDD+.+codger+.+sello+.+idusuarioointranet quien altero',
  `sessionficha` VARCHAR(40) NULL DEFAULT NULL COMMENT 'YYYYMMDD+.+codger+.+sello+.+idusuarioointranet quien lo creo',
  PRIMARY KEY (`cod_localidad`))
COMMENT = 'codigo de la ubicacion o sitio o localidad';


-- -----------------------------------------------------
-- Table `adm_log_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `adm_log_usuario` ;

CREATE TABLE IF NOT EXISTS `adm_log_usuario` (
  `cod_log_usuario` VARCHAR(40) NOT NULL COMMENT 'YYYYMMDDhhmmss . sello . intranet',
  `ref_direccionip` VARCHAR(40) NULL DEFAULT NULL COMMENT 'ip cliente',
  `ref_url` VARCHAR(40) NULL DEFAULT NULL COMMENT 'url controlador o app que invoco',
  PRIMARY KEY (`cod_log_usuario`))
COMMENT = 'chismoso log para administrativo';


-- -----------------------------------------------------
-- Table `adm_perfil`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `adm_perfil` ;

CREATE TABLE IF NOT EXISTS `adm_perfil` (
  `cod_perfil` VARCHAR(40) NOT NULL COMMENT 'nombre codigo de este perfil',
  `cod_controlador` VARCHAR(40) NOT NULL COMMENT 'archivo o codigo que accede',
  `cod_aplicacion` VARCHAR(40) NOT NULL COMMENT 'nombre del sistema que accede',
  `des_perfil` VARCHAR(40) NULL DEFAULT NULL COMMENT 'descripcion del perfil',
  `sessionflag` VARCHAR(40) NULL DEFAULT NULL COMMENT 'quien altero YYYYMMDDhhmmss+codger+.+user',
  `sesionficha` VARCHAR(40) NULL DEFAULT NULL COMMENT 'quien lo creo YYYYMMDDhhmmss+codger+.+user',
  PRIMARY KEY (`cod_perfil`, `cod_controlador`, `cod_aplicacion`))
COMMENT = 'perfiles y que sistema accede';


-- -----------------------------------------------------
-- Table `adm_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `adm_usuario` ;

CREATE TABLE IF NOT EXISTS `adm_usuario` (
  `ficha` VARCHAR(40) NOT NULL COMMENT 'id usuario, cedula en vnzla',
  `intranet` VARCHAR(40) NOT NULL COMMENT 'login del usuario, id del correo',
  `clave` VARCHAR(40) NULL DEFAULT NULL COMMENT 'clave de intranet',
  `nombre` VARCHAR(400) NULL DEFAULT NULL COMMENT 'nombre y apellido',
  `detalles` VARCHAR(400) NULL DEFAULT NULL COMMENT 'datos extra del usuario',
  `estado` VARCHAR(40) NOT NULL DEFAULT 'INACTIVO' COMMENT 'ACTIVO|INACTIVO|SUSPENDIDO',
  `tipo_usuario` VARCHAR(40) NULL DEFAULT NULL COMMENT 'ESPECIAL|ADMINISTRATIVO|NORMAL',
  `cod_perfil` VARCHAR(400) NULL DEFAULT NULL COMMENT 'Permite determinar el nivel de usuario para los accesos de lectura, escritura  y modificación en la BD',
  `log_usuario` VARCHAR(400) NULL DEFAULT NULL COMMENT 'codigo de registro de actividad de este usuario',
  `reservado2` VARCHAR(400) NULL DEFAULT NULL COMMENT 'donde y que puede modificar gastos',
  `fecha_ultimavez` VARCHAR(40) NULL DEFAULT NULL COMMENT 'ultimo registro administrativo',
  `sessionflag` VARCHAR(40) NULL DEFAULT NULL COMMENT 'YYYYMMDD+.+codger+.+sello+.+idusuarioointranet quien altero',
  `sessionficha` VARCHAR(40) NULL DEFAULT NULL COMMENT 'YYYYMMDD+.+codger+.+sello+.+idusuarioointranet quien lo creo',
  PRIMARY KEY (`intranet`, `ficha`))
COMMENT = 'tabla principal usuarios';


-- -----------------------------------------------------
-- Table `sys_idiomas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sys_idiomas` ;

CREATE TABLE IF NOT EXISTS `sys_idiomas` (
  `cod_idioma` VARCHAR(40) NOT NULL COMMENT 'ES|EN|RU|EL etc',
  `des_idioma` VARCHAR(40) NULL DEFAULT NULL COMMENT 'Idioma nativo escrito en su lengua',
  PRIMARY KEY (`cod_idioma`))
COMMENT = 'tabla de identificacion de los idiomas';


-- -----------------------------------------------------
-- Table `sys_descripcion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sys_descripcion` ;

CREATE TABLE IF NOT EXISTS `sys_descripcion` (
  `cod_descripcion` VARCHAR(40) NOT NULL COMMENT 'DESYYYYMMDDhhmmss identificador de la descripcion en el idioma especifico',
  `cod_idioma` VARCHAR(40) NOT NULL DEFAULT 'ES' COMMENT 'ES|EN|RU|EL y asi',
  `des_descripcion` VARCHAR(400) NULL DEFAULT NULL COMMENT 'descripcion en el idioma especifico',
  `sessionflag` VARCHAR(40) NULL DEFAULT NULL COMMENT 'YYYYMMDDhhmmss . entidad . intranet : quien cambio este registro',
  PRIMARY KEY (`cod_descripcion`, `cod_idioma`))
COMMENT = 'descripciones por idioma de cada codigo descripcion de los s' /* comment truncated */ /*istemas*/;


-- -----------------------------------------------------
-- Data for table `nom_user_registers`
-- -----------------------------------------------------
INSERT INTO `nom_user_registers` (`cod_user`, `email`, `userpass`, `api_token`, `userlevel`, `created_at`, `updated_at`) VALUES ('123', 'demo', 'demo', 'token', '1', '20230101', '20230101');


-- -----------------------------------------------------
-- Data for table `nom_user_profile`
-- -----------------------------------------------------
INSERT INTO `nom_user_profile` (`cod_user`, `first_name`, `second_name`, `last_name`, `second_surname`, `presentation`, `education_level`, `address_born`, `address_living`, `first_phone`, `second_phone`, `picture_face`, `picture_body`, `created_at`, `updated_at`) VALUES ('123', 'name', 'surape', 'apellid', 'overname', 'i am a employer', '2', 'venezuela, city, address, home number', 'colombia, city, address, home floor', '+582122661610', '+502125556677', 'storage/files/face.jpeg', NULL, '20240101', '20240101');


-- -----------------------------------------------------
-- Data for table `nom_vacancies_details`
-- -----------------------------------------------------
INSERT INTO `nom_vacancies_details` (`cod_vacancies`, `is_permanent`, `vacancies_name`, `vacancies_description`, `vacancies_direction`, `vacancies_start`, `vacancies_end`, `created_at`, `updated_at`) VALUES ('1', '0', 'Gerente', 'Manager for loren ipsum loren ipsum', 'Calle paez cruze con bolivar', '20240131', '20240220', '20240130', '20240130');


-- -----------------------------------------------------
-- Data for table `nom_vacancies_tag`
-- -----------------------------------------------------
INSERT INTO `nom_vacancies_tag` (`cod_vacancies_tag`, `des_vacancies_tag`, `created_at`, `updated_at`) VALUES ('Legal', 'Abogado, Politica, Policia, Juez, Jurado', '20240101', '20240101');
INSERT INTO `nom_vacancies_tag` (`cod_vacancies_tag`, `des_vacancies_tag`, `created_at`, `updated_at`) VALUES ('Artes', 'Diseño grafico, Marqueting', '20240101', '20240101');
INSERT INTO `nom_vacancies_tag` (`cod_vacancies_tag`, `des_vacancies_tag`, `created_at`, `updated_at`) VALUES ('Salud', 'Agronomía, Fisioterapia, Antropología, Enfermería, Odontología', '20240101', '20240101');
INSERT INTO `nom_vacancies_tag` (`cod_vacancies_tag`, `des_vacancies_tag`, `created_at`, `updated_at`) VALUES ('Admin', 'Archivología, Gerente, Sub Gerente, Administradora', '20240101', '20240101');
INSERT INTO `nom_vacancies_tag` (`cod_vacancies_tag`, `des_vacancies_tag`, `created_at`, `updated_at`) VALUES ('Ingenieria', 'Civil, Arquitectura, Soporte Tecnico, Electrica, Mecanica', '20240101', '20240101');
INSERT INTO `nom_vacancies_tag` (`cod_vacancies_tag`, `des_vacancies_tag`, `created_at`, `updated_at`) VALUES ('Ciencias', 'Contaduría, Computación, Estadística, Reportes, Geografía, Química', '20240101', '20240101');
INSERT INTO `nom_vacancies_tag` (`cod_vacancies_tag`, `des_vacancies_tag`, `created_at`, `updated_at`) VALUES ('Comunica', 'Abogado, Politica, Gerencia, Auditoria, Filosofía, Idiomas, Psicología, Comunicacion', '20240101', '20240101');
INSERT INTO `nom_vacancies_tag` (`cod_vacancies_tag`, `des_vacancies_tag`, `created_at`, `updated_at`) VALUES ('Economia', 'Negocios, Compras, Tesoreria, Finanzas, Economia', '20240101', '20240101');
INSERT INTO `nom_vacancies_tag` (`cod_vacancies_tag`, `des_vacancies_tag`, `created_at`, `updated_at`) VALUES ('Educacion', 'Educacion, Cursos, Historia', '20240101', '20240101');
INSERT INTO `nom_vacancies_tag` (`cod_vacancies_tag`, `des_vacancies_tag`, `created_at`, `updated_at`) VALUES ('Procesos', 'Procesos Industriales, Gerencia de procesos', '20240101', '20240101');


-- -----------------------------------------------------
-- Data for table `nom_vacancies`
-- -----------------------------------------------------
INSERT INTO `nom_vacancies` (`cod_vacancies`, `cod_vacancies_tag`, `vacancies_title`, `created_at`, `updated_at`) VALUES ('1', 'Admin', 'Gerente for manager', '20240131', '20240131');

